version: 2
updates:
  # Enable version updates for npm
  - package-ecosystem: npm
    # Look for `package.json` and `lock` files in the `root` directory
    directory: /
    # Check the npm registry for updates every first day of the month at 6am
    schedule:
      interval: monthly
      timezone: America/Detroit
      time: 06:00
    # Exclude `chai` as it is a breaking change
    ignore:
      - dependency-name: chai
    # Assign to the lead developer
    assignees:
      - erinesullivan
    # Add the `dependencies` label
    labels:
      - dependencies
    # Let dependabot create up to 10 PRs at a time
    open-pull-requests-limit: 10

  # Enable version updates for GitHub Actions
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: monthly
      timezone: America/Detroit
      time: 06:00
    assignees:
      - erinesullivan
    labels:
      - dependencies