name: Update PR Title

on:
  pull_request:
    types: [opened, synchronize, labeled, unlabeled]

jobs:
  update-pr-title:
    runs-on: ubuntu-latest
    if: github.actor == 'erinesullivan'
    steps:
      - name: Check PR label
        id: check_label
        uses: actions/github-script@v7
        with:
          script: |
            const prLabels = context.payload.pull_request.labels;
            const hasDependenciesLabel = prLabels.some(label => label.name === 'invalid');
            return hasDependenciesLabel;

      - name: Update PR title
        if: steps.check_label.outputs.result == 'true'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          sudo apt-get update
          sudo apt-get install -y gh
          CURRENT_DATE=$(date +"%B %Y")
          NEW_TITLE="${CURRENT_DATE} dependency updates"
          PR_NUMBER="${{ github.event.pull_request.number }}"
          gh pr edit $PR_NUMBER --title "$NEW_TITLE"
