name: Update PR Title

on:
  pull_request:
    types: [opened]

jobs:
  update-pr:
    runs-on: ubuntu-latest
    if: github.actor == 'erinesullivan'

    steps:
      - name: Update PR title
        uses: actions/github-script@v7
        with:
          script: |
            const monthNames = [
              "January", "February", "March", "April", "May", "June",
              "July", "August", "September", "October", "November", "December"
            ];
            const now = new Date();
            const month = monthNames[now.getMonth()];
            const year = now.getFullYear();
            const title = `${month} ${year} dependency updates.`;
            
            await github.pulls.update({
              owner: context.repo.owner,
              repo: context.repo.repo,
              pull_number: context.payload.pull_request.number,
              title: title
            });