#  Name of workflow
name: Build workflow

# When workflow is triggered
on:
  push:
    branches:
      - master

# Jobs to carry out
jobs:
  build-and-test:
    # Use reusable workflow
    uses: ./.github/workflows/build-and-test.yml
